### PR TITLE
Removed forum link from header, renamed "Project" to "About Duality"

### PR DESCRIPTION
**Pull request by ilexp**
### Summary

See PR title. This is related to the latest status update [here](https://github.com/AdamsLair/duality/issues/707#issuecomment-636461203).

### CODE REVIEW

**Comment by Rick-van-Dam** [comment]
Maybe replace the link with a link to the discord ?

**Comment by ilexp** [comment]
The existing chat link right next to it is already a link to the discord 🙂

**Comment by Rick-van-Dam** [comment]
Ah missed that. Ignore my now silly comment then XD

**Comment by ilexp** [comment]
So.. if that's it, can anyone approve this? 😄

**Review by SirePi — APPROVED** [review]

**Pull request merged**
