### PR TITLE
#31 - Formatting correction to v2 documents

### PR DESCRIPTION
**Pull request by BobGneu**
### Summary

Corrects formatting issue on v2 document where the preformatted text block doesnt have the proper suffix. 

### Article Checklist

- [ ] A table-of-contents marker is present below the article summary, above the first chapter.
- [ ] Spell checking software doesn't complain.
- [ ] All images are part of the PR, or already in the repository.
- [ ] All links are verified to work.
- [ ] Language used is (overall) clean, precise and to the point.

### Technical Checklist

- [ ] Provide a bulleted list of changes that are introduced by this PR.
- [ ] Screenshots of before / after for style and layout related changes.

### CODE REVIEW

**Comment by BobGneu** [comment]
Corrected the section header.

**Comment by ilexp** [comment]
Is there something wrong with this PR? When I click on the changes tab, it tells me that nothing has changed at all?

**Comment by BobGneu** [comment]
Same. taking a look.

**Comment by BobGneu** [comment]
Looks like you pushed these changes already. Closing this one out.

**Pull request closed without merging**
