### PR TITLE
Updated Duality-Docs Style and Jekyll Template

### PR DESCRIPTION
**Pull request by ilexp**
Latest style and template changes after adopting the new PR-based dev process. See issue #3 for more details.

This PR includes, roughly:

- Multi-version support for sidebar.
- Various sidebar behavior tweaks with nested pages.
- Table of contents in Getting Started, and table of contents style.
- Syntax highlighting colors and style updated.
- Sidebar links now point to each pages content anchor in the low-width responsive style variant.
- Responsive table style to remain more readable on low width.
- Added a Duality favicon.

Still work in progress, but almost done. When merging later on, consider a squash merge to avoid cluttering repo history with all those small / temp / wip commits.

A preview of the changes in action can be seen [here](https://ilexp.github.io/duality-docs/).

### CODE REVIEW

**Comment by ilexp** [comment]
Alright, I'm done with this for now. Please review and do a squash merge on approval.

**Comment by ChristianGreiner** [comment]
**1. Images not included** 
- [Creating Bullet-like Objects](https://ilexp.github.io/duality-docs/pages/v2/Creating-Bullet-like-Objects.html)
- [Working with Animations](https://ilexp.github.io/duality-docs/pages/v2/Working-With-Animations.html)
- [Using Tilemaps ](https://ilexp.github.io/duality-docs/pages/v2/Tilemaps.html)
image
- https://ilexp.github.io/duality-docs/pages/v2/Project-Version-History.html

**2. In my option I would remove the boarder from the icons (startpage)**
With boarder:
image

Without boarder:
image

**3. Syntax highlighting missing**
https://ilexp.github.io/duality-docs/pages/v2/Custom-Renderers.html

**4. Table formatting**
The list of community projects looks quite "broken" (see headline)
https://ilexp.github.io/duality-docs/pages/v2/List-of-Community-Projects.html

All in all the page looks nice 👍

**Comment by ilexp** [comment]
> 1. Images not included

This is a content issue, to be addressed in #2. Not a part of this PR.

> 2. In my option I would remove the boarder from the icons (startpage)

Agree and would like to remove them as well. However, as far as I know there is no way to provide parameters to images using pure markdown, and the home page is just a regular content page. This leaves us with one style for images in page content - with borders or without borders. Given this constraint, I'm in favor of bordered images to achieve a "figure X" like appearance for the actual content, as you can see in [Getting Started](https://ilexp.github.io/duality-docs/pages/v2/getting-started.html#editing-gameobjects).

As long as we don't have a solution for this, I'd just go with the border version, since that works well for regular "article style" content pages, which are the large majority.

> 3. Syntax highlighting missing

This is a content issue, either to be addressed in #2, or in a new issue that isn't filed yet. Not a part of this PR.

> 4. Table formatting

Ah, that's definitely broken. Looks like I'll need to remove the `table-layout: fixed` again. Will do!

**Comment by ilexp** [comment]
Tweaked a bit more on how tables are displayed in various window sizes, should be a lot better now.

**Comment by ilexp** [comment]
Removed image borders when in tables. I think this could be a good middle ground for point 2, as we can assume tables to already provide a sort of framing for an image.

**Review by ChristianGreiner — APPROVED** [review]
Looks good now! 👍

**Pull request merged**
